name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.1

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download Windows artifact
        id: download-win-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: windows.yml
          workflow_conclusion: success
          repo: adastralgroup/winter
      - name: Download Linux artifact
        id: download-lin-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          repo: adastralgroup/winter 
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libnotify-dev libnotify4
          version: 1.0
      - name: Setup
        run: |
          cp linux/* bin/
          cp windows/* bin/
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export-debug --headless "Windows Desktop" build/windows/adastral.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows/
          
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          repo: adastralgroup/winter
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libnotify-dev libnotify4
          version: 1.0    
      - name: Setup
        run: |
          cp linux/* bin/
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export-debug --headless "Linux/X11" build/linux/adastral.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
